### ISSUE TITLE
add switch for path to tmux

### ISSUE THREAD

**Issue by bmedicke** [Russell91/sshmux#1]
Great idea! This makes me miss mosh a whole lot less on servers where I have little control. I hope you'll add it to homebrew.

An option to specify the path to tmux would be useful.

**Comment by Russell91** [comment]
Homebrew is a great idea. I'll try to look into that when I have the time. I'd like to avoid just adding flags arbitrarily as each flag steadily detracts from the notion that it is just a lightweight wrapper around ssh. But an environment variable could work for this. Do you mind detailing your use case? I'm assuming that this would allow you to avoid having tmux as a root install on the server, but maybe there is something else going on as well?

**Comment by bmedicke** [comment]
Yeah, that's pretty much it. If I can't set up mosh I probably can't guarantee that tmux is in the path.

**Comment by Russell91** [comment]
Okay, I believe this has been addressed by https://github.com/Russell91/sshmux/commit/e52ec92027fb51f49f1fecbe35f13164fb242729.

**Comment by bmedicke** [comment]
Great solution, thank you.
